-- Fresh PostgreSQL schema. The previous runtime database was in-memory H2, so there
-- is no automatic data import in this migration.

CREATE TABLE users (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        varchar(255),
    username                    varchar(16)  NOT NULL,
    token                       varchar(255) NOT NULL,
    status                      varchar(32)  NOT NULL,
    bio                         varchar(180) NOT NULL DEFAULT '',
    creation_date               date         NOT NULL,
    profile_character_id        varchar(255) NOT NULL DEFAULT 'char01',
    menu_background_id          varchar(255) NOT NULL DEFAULT 'menu-bg-1',
    game_background_id          varchar(255) NOT NULL DEFAULT 'game-bg-1',
    primary_color_id            varchar(255) NOT NULL DEFAULT 'orange',
    appearance_mode             varchar(255) NOT NULL DEFAULT 'system',
    tutorials_enabled           boolean,
    music_volume                integer      NOT NULL DEFAULT 10,
    sound_effects_volume        integer      NOT NULL DEFAULT 30,
    games_won                   integer      NOT NULL DEFAULT 0,
    rounds_won                  integer      NOT NULL DEFAULT 0,
    average_score_per_session   integer      NOT NULL DEFAULT 0,
    average_score_per_round     integer      NOT NULL DEFAULT 0,
    overall_rank                integer      NOT NULL DEFAULT 0,
    is_public_log               boolean      NOT NULL DEFAULT true,
    password                    varchar(255) NOT NULL,
    last_heartbeat              timestamp with time zone,
    games_played                integer      NOT NULL DEFAULT 0,
    games_lost                  integer      NOT NULL DEFAULT 0,
    total_points_accumulated    integer      NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_token UNIQUE (token),
    CONSTRAINT ck_users_status CHECK (status IN ('ONLINE', 'OFFLINE', 'LOBBY', 'PLAYING', 'SPECTATING')),
    CONSTRAINT ck_users_music_volume CHECK (music_volume BETWEEN 0 AND 100),
    CONSTRAINT ck_users_sound_effects_volume CHECK (sound_effects_volume BETWEEN 0 AND 100),
    CONSTRAINT ck_users_stats_nonnegative CHECK (
        games_won >= 0 AND rounds_won >= 0 AND games_played >= 0
        AND games_lost >= 0 AND total_points_accumulated >= 0
    )
);

CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_last_heartbeat ON users (last_heartbeat) WHERE last_heartbeat IS NOT NULL;

CREATE TABLE user_preferred_color_priority (
    user_id         bigint       NOT NULL,
    color           varchar(255) NOT NULL,
    priority_index  integer      NOT NULL,
    PRIMARY KEY (user_id, priority_index),
    CONSTRAINT fk_user_color_priority_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_music_blacklist (
    user_id    bigint       NOT NULL,
    track_tag  varchar(255) NOT NULL,
    tag_index  integer      NOT NULL,
    PRIMARY KEY (user_id, tag_index),
    CONSTRAINT fk_user_music_blacklist_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_friend_ids (
    user_id         bigint NOT NULL,
    friend_user_id  bigint,
    CONSTRAINT fk_user_friend_ids_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_friend_ids_user_id ON user_friend_ids (user_id);
CREATE INDEX idx_user_friend_ids_friend_user_id ON user_friend_ids (friend_user_id);

CREATE TABLE sessions (
    id                                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id                             varchar(255)             NOT NULL,
    start_time                             timestamp with time zone NOT NULL,
    is_ended                               boolean                  NOT NULL DEFAULT false,
    absent_round_points                    bigint                   NOT NULL DEFAULT 20,
    user_scores_per_round                  jsonb                    NOT NULL DEFAULT '[]'::jsonb,
    total_score_by_user_id                 jsonb                    NOT NULL DEFAULT '{}'::jsonb,
    hundred_reduction_applied_by_user_id   jsonb                    NOT NULL DEFAULT '{}'::jsonb,
    winner_ids                             jsonb,
    CONSTRAINT uk_sessions_session_id UNIQUE (session_id),
    CONSTRAINT ck_sessions_absent_round_points_nonnegative CHECK (absent_round_points >= 0)
);

CREATE INDEX idx_sessions_ended_start_time ON sessions (is_ended, start_time);

CREATE TABLE lobbies (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id               varchar(255) NOT NULL,
    session_host_user_id     bigint       NOT NULL,
    is_public                boolean      NOT NULL DEFAULT true,
    current_round            integer      NOT NULL DEFAULT 0,
    status                   varchar(255) NOT NULL DEFAULT 'WAITING',
    player_set_key           varchar(256) NOT NULL DEFAULT '',
    afk_timeout_seconds      bigint       NOT NULL DEFAULT 300,
    initial_peek_seconds     bigint       NOT NULL DEFAULT 10,
    turn_seconds             bigint       NOT NULL DEFAULT 30,
    ability_reveal_seconds   bigint       NOT NULL DEFAULT 5,
    ability_swap_seconds     bigint       NOT NULL DEFAULT 10,
    absent_round_points      bigint       NOT NULL DEFAULT 20,
    websocket_grace_seconds  bigint       NOT NULL DEFAULT 300,
    chat_cooldown_seconds    bigint       NOT NULL DEFAULT 3,
    CONSTRAINT uk_lobbies_session_id UNIQUE (session_id),
    CONSTRAINT ck_lobbies_current_round_nonnegative CHECK (current_round >= 0),
    CONSTRAINT ck_lobbies_status CHECK (status IN ('WAITING', 'PLAYING')),
    CONSTRAINT ck_lobbies_timers_positive CHECK (
        afk_timeout_seconds > 0 AND initial_peek_seconds > 0 AND turn_seconds > 0
        AND ability_reveal_seconds > 0 AND ability_swap_seconds > 0
        AND websocket_grace_seconds > 0 AND chat_cooldown_seconds > 0
    ),
    CONSTRAINT ck_lobbies_absent_round_points_nonnegative CHECK (absent_round_points >= 0)
);

CREATE INDEX idx_lobby_status_player_set_key ON lobbies (status, player_set_key);
CREATE INDEX idx_lobbies_session_host_user_id ON lobbies (session_host_user_id);

CREATE TABLE lobby_player_ids (
    lobby_id    bigint NOT NULL,
    player_ids  bigint,
    CONSTRAINT fk_lobby_player_ids_lobby
        FOREIGN KEY (lobby_id) REFERENCES lobbies (id) ON DELETE CASCADE
);

CREATE INDEX idx_lobby_player_ids_player_id ON lobby_player_ids (player_ids);
CREATE INDEX idx_lobby_player_ids_lobby_id ON lobby_player_ids (lobby_id);

CREATE TABLE lobby_kicked_user_ids (
    lobby_id         bigint NOT NULL,
    kicked_user_ids  bigint,
    CONSTRAINT fk_lobby_kicked_user_ids_lobby
        FOREIGN KEY (lobby_id) REFERENCES lobbies (id) ON DELETE CASCADE
);

CREATE INDEX idx_lobby_kicked_user_ids_lobby_id ON lobby_kicked_user_ids (lobby_id);
CREATE INDEX idx_lobby_kicked_user_ids_user_id ON lobby_kicked_user_ids (kicked_user_ids);

CREATE TABLE lobby_spectator_ids (
    lobby_id      bigint NOT NULL,
    spectator_ids bigint,
    CONSTRAINT fk_lobby_spectator_ids_lobby
        FOREIGN KEY (lobby_id) REFERENCES lobbies (id) ON DELETE CASCADE
);

CREATE INDEX idx_lobby_spectator_ids_user_id ON lobby_spectator_ids (spectator_ids);
CREATE INDEX idx_lobby_spectator_ids_lobby_id ON lobby_spectator_ids (lobby_id);

CREATE TABLE lobby_assigned_character_color (
    lobby_id  bigint       NOT NULL,
    user_id   bigint       NOT NULL,
    color_id  varchar(255) NOT NULL,
    PRIMARY KEY (lobby_id, user_id),
    CONSTRAINT fk_lobby_assigned_character_color_lobby
        FOREIGN KEY (lobby_id) REFERENCES lobbies (id) ON DELETE CASCADE
);

CREATE TABLE lobby_player_ready_state (
    lobby_id  bigint  NOT NULL,
    user_id   bigint  NOT NULL,
    is_ready  boolean NOT NULL,
    PRIMARY KEY (lobby_id, user_id),
    CONSTRAINT fk_lobby_player_ready_state_lobby
        FOREIGN KEY (lobby_id) REFERENCES lobbies (id) ON DELETE CASCADE
);

CREATE TABLE games (
    id                              varchar(36)              PRIMARY KEY,
    deck_api_id                     varchar(255),
    draw_pile                       jsonb                    NOT NULL DEFAULT '[]'::jsonb,
    discard_pile                    jsonb                    NOT NULL DEFAULT '[]'::jsonb,
    player_hands                    jsonb                    NOT NULL DEFAULT '{}'::jsonb,
    ordered_player_ids              jsonb                    NOT NULL DEFAULT '[]'::jsonb,
    drawn_card                      jsonb,
    status                          varchar(32)              NOT NULL DEFAULT 'INTRO',
    initial_peek_done_by_user_id    jsonb                    NOT NULL DEFAULT '{}'::jsonb,
    drawn_from_deck                 boolean                  NOT NULL DEFAULT false,
    is_cabo_called                  boolean,
    cabo_called_by_user_id          bigint,
    cabo_forced_by_timeout          boolean                  NOT NULL DEFAULT false,
    special_peek_used               boolean                  NOT NULL DEFAULT false,
    turn_seconds                    bigint                   NOT NULL DEFAULT 30,
    initial_peek_seconds            bigint                   NOT NULL DEFAULT 10,
    ability_reveal_seconds          bigint                   NOT NULL DEFAULT 5,
    ability_swap_seconds            bigint                   NOT NULL DEFAULT 10,
    cabo_reveal_seconds             bigint                   NOT NULL DEFAULT 30,
    rematch_decision_seconds        bigint                   NOT NULL DEFAULT 60,
    afk_timeout_seconds             bigint                   NOT NULL DEFAULT 300,
    rematch_decision_by_user_id     jsonb                    NOT NULL DEFAULT '{}'::jsonb,
    fresh_rematch_requester_user_id bigint,
    round_ended_at                  timestamp with time zone,
    last_move_event                 jsonb,
    last_move_sequence              bigint                   NOT NULL DEFAULT 0,
    current_player_id               bigint,
    resumed_from_session_id         bigint,
    CONSTRAINT ck_games_status CHECK (status IN (
        'INTRO', 'INITIAL_PEEK', 'ROUND_ACTIVE', 'ABILITY_PEEK_SELF',
        'ABILITY_PEEK_OPPONENT', 'ABILITY_SWAP', 'CABO_REVEAL',
        'ROUND_AWAITING_REMATCH', 'ROUND_ENDED'
    )),
    CONSTRAINT ck_games_timers_positive CHECK (
        turn_seconds > 0 AND initial_peek_seconds > 0 AND ability_reveal_seconds > 0
        AND ability_swap_seconds > 0 AND cabo_reveal_seconds > 0
        AND rematch_decision_seconds > 0 AND afk_timeout_seconds > 0
    ),
    CONSTRAINT ck_games_last_move_sequence_nonnegative CHECK (last_move_sequence >= 0)
);

CREATE INDEX idx_games_status ON games (status);
CREATE INDEX idx_games_status_round_ended_at ON games (status, round_ended_at);
CREATE INDEX idx_games_ordered_player_ids_gin ON games USING gin (ordered_player_ids);

CREATE TABLE moves (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   varchar(255)             NOT NULL,
    user_id      bigint                   NOT NULL,
    action_type  varchar(255)             NOT NULL,
    timestamp    timestamp with time zone NOT NULL,
    details      varchar(255),
    is_public    boolean                  NOT NULL DEFAULT false
);

CREATE INDEX idx_moves_session_timestamp ON moves (session_id, timestamp);
CREATE INDEX idx_moves_user_id ON moves (user_id);

CREATE TABLE cabo_invites (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  bigint                   NOT NULL,
    to_user_id    bigint                   NOT NULL,
    lobby_id      bigint,
    status        varchar(32)              NOT NULL DEFAULT 'PENDING',
    created_at    timestamp without time zone NOT NULL,
    CONSTRAINT ck_cabo_invites_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED'))
);

CREATE INDEX idx_cabo_invites_to_status_created
    ON cabo_invites (to_user_id, status, created_at);
CREATE INDEX idx_cabo_invites_from_lobby_created
    ON cabo_invites (from_user_id, lobby_id, created_at);
CREATE INDEX idx_cabo_invites_lobby_status
    ON cabo_invites (lobby_id, status);
